routes:

  # list of routes

  root:
    default: true
    url: /
    templateUrl: root.html
    resolve:
      translations: translationsLoader

    ./:
      home:
        default: true
        url: home
        templateUrl: home/home.html
        controller: HomeController

      somewhere:
        url: somewhere
        templateUrl: somewhere/somewhere.html
        controller: SomewhereController

      error:
        url: error
        templateUrl: error/error.html

        ./:
          err404:
            default: true
            url: /404
            templateUrl: error/error-404.html
            controller: HomeController